# Generated by Django 4.2.5 on 2023-11-17 21:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("profiles", "0003_alter_companyprofile_user_alter_userprofile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="about",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="achievements",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="age",
            field=models.PositiveIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="education",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="languages",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="profile_image",
            field=models.ImageField(upload_to="profile_image/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="programming_languages",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="stack",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                related_name="profiler",
                serialize=False,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="work_experience",
            field=models.TextField(),
        ),
    ]
