# Generated by Django 4.2.5 on 2023-11-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type_post', models.CharField(choices=[('Work', 'Work'), ('Teams', 'Teams')], max_length=5)),
                ('description', models.TextField()),
                ('celery', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('celery', models.PositiveIntegerField()),
                ('type_work', models.CharField(choices=[('Work', 'Work'), ('Internship', 'Internship')], max_length=10)),
                ('type_employment', models.CharField(choices=[('Office', 'Office'), ('Online', 'Online')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='ErCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='ercode_file/')),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='forum_file/')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type_post', models.CharField(choices=[('Work', 'Work'), ('Teams', 'Teams')], max_length=5)),
                ('description', models.TextField()),
                ('celery', models.PositiveIntegerField()),
            ],
        ),
    ]
