# Generated by Django 4.2.5 on 2023-11-28 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companypost',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='companyvacancy',
            name='position',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='companyvacancy',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='ercode',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='forum',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='post',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
