# Generated by Django 4.2.5 on 2023-11-28 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='status',
        ),
        migrations.AlterField(
            model_name='resume',
            name='applied_vacancies',
            field=models.ManyToManyField(blank=True, related_name='applicants_resumes', to='post.companyvacancy'),
        ),
    ]
